version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: 502257142405.dkr.ecr.ap-south-1.amazonaws.com/my-app:1.0
    ports:
      - 3000:3000
volumes:
  mongodb-data:
    driver: local